import { ResolvedConfig } from '../../types/config';

export const SUBTITLE_DEFAULT_CONFIG: Pick<ResolvedConfig, 'subtitleStyle' | 'subtitleSidebar'> = {
  subtitleStyle: {
    primaryDefaultMode: 'visible',
    enableJlpt: false,
    preserveLineBreaks: false,
    autoPauseVideoOnHover: true,
    autoPauseVideoOnYomitanPopup: true,
    hoverTokenColor: '#f4dbd6',
    hoverTokenBackgroundColor: 'rgba(54, 58, 79, 0.84)',
    nameMatchEnabled: true,
    nameMatchColor: '#f5bde6',
    fontFamily: 'M PLUS 1 Medium, Source Han Sans JP, Noto Sans CJK JP',
    fontSize: 35,
    fontColor: '#cad3f5',
    fontWeight: '600',
    lineHeight: 1.35,
    letterSpacing: '-0.01em',
    wordSpacing: 0,
    fontKerning: 'normal',
    textRendering: 'geometricPrecision',
    textShadow: '0 3px 10px rgba(0,0,0,0.69)',
    fontStyle: 'normal',
    backgroundColor: 'rgb(30, 32, 48, 0.88)',
    backdropFilter: 'blur(6px)',
    nPlusOneColor: '#c6a0f6',
    knownWordColor: '#a6da95',
    jlptColors: {
      N1: '#ed8796',
      N2: '#f5a97f',
      N3: '#f9e2af',
      N4: '#a6e3a1',
      N5: '#8aadf4',
    },
    frequencyDictionary: {
      enabled: false,
      sourcePath: '',
      topX: 1000,
      mode: 'single',
      matchMode: 'headword',
      singleColor: '#f5a97f',
      bandedColors: ['#ed8796', '#f5a97f', '#f9e2af', '#8bd5ca', '#8aadf4'],
    },
    secondary: {
      fontFamily: 'Inter, Noto Sans, Helvetica Neue, sans-serif',
      fontSize: 24,
      fontColor: '#cad3f5',
      lineHeight: 1.35,
      letterSpacing: '-0.01em',
      wordSpacing: 0,
      fontKerning: 'normal',
      textRendering: 'geometricPrecision',
      textShadow: '0 2px 4px rgba(0,0,0,0.95), 0 0 8px rgba(0,0,0,0.8), 0 0 16px rgba(0,0,0,0.55)',
      backgroundColor: 'rgba(20, 22, 34, 0.78)',
      backdropFilter: 'blur(6px)',
      fontWeight: '600',
      fontStyle: 'normal',
    },
  },
  subtitleSidebar: {
    enabled: true,
    autoOpen: false,
    layout: 'overlay',
    toggleKey: 'Backslash',
    pauseVideoOnHover: false,
    autoScroll: true,
    maxWidth: 420,
    opacity: 0.95,
    backgroundColor: 'rgba(73, 77, 100, 0.9)',
    textColor: '#cad3f5',
    fontFamily: '"M PLUS 1", "Noto Sans CJK JP", sans-serif',
    fontSize: 16,
    timestampColor: '#a5adcb',
    activeLineColor: '#f5bde6',
    activeLineBackgroundColor: 'rgba(138, 173, 244, 0.22)',
    hoverLineBackgroundColor: 'rgba(54, 58, 79, 0.84)',
  },
};
