import { ResolvedConfig } from '../../types/config';

export const SUBTITLE_DEFAULT_CONFIG: Pick<ResolvedConfig, 'subtitleStyle' | 'subtitleSidebar'> = {
  subtitleStyle: {
    primaryDefaultMode: 'visible',
    css: {},
    enableJlpt: false,
    preserveLineBreaks: false,
    autoPauseVideoOnHover: true,
    autoPauseVideoOnYomitanPopup: true,
    primaryVisibleOnYomitanPopup: true,
    hoverTokenColor: '#f4dbd6',
    hoverTokenBackgroundColor: 'transparent',
    nameMatchEnabled: false,
    nameMatchImagesEnabled: false,
    nameMatchColor: '#f5bde6',
    fontFamily: 'Hiragino Sans, M PLUS 1, Source Han Sans JP, Noto Sans CJK JP',
    fontSize: 35,
    fontColor: '#cad3f5',
    fontWeight: '600',
    lineHeight: 1.35,
    letterSpacing: '-0.01em',
    wordSpacing: 0,
    fontKerning: 'normal',
    textRendering: 'geometricPrecision',
    textShadow:
      '-1px -1px 2px rgba(0,0,0,0.95), 1px -1px 2px rgba(0,0,0,0.95), -1px 1px 2px rgba(0,0,0,0.95), 1px 1px 2px rgba(0,0,0,0.95), 0 0 8px rgba(0,0,0,0.5)',
    paintOrder: '',
    WebkitTextStroke: '',
    fontStyle: 'normal',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(6px)',
    nPlusOneColor: '#c6a0f6',
    knownWordColor: '#a6da95',
    knownWordMaturityColors: {
      new: '#ee99a0',
      learning: '#b7bdf8',
      young: '#91d7e3',
      mature: '#a6da95',
    },
    jlptColors: {
      N1: '#ed8796',
      N2: '#f5a97f',
      N3: '#f9e2af',
      N4: '#8bd5ca',
      N5: '#8aadf4',
    },
    frequencyDictionary: {
      enabled: false,
      sourcePath: '',
      topX: 10000,
      mode: 'single',
      matchMode: 'headword',
      singleColor: '#f5a97f',
      bandedColors: ['#ed8796', '#f5a97f', '#f9e2af', '#8bd5ca', '#8aadf4'],
    },
    secondary: {
      css: {},
      fontFamily: 'Hiragino Sans, M PLUS 1, Source Han Sans JP, Noto Sans CJK JP',
      fontSize: 24,
      fontColor: '#cad3f5',
      lineHeight: 1.35,
      letterSpacing: '-0.01em',
      wordSpacing: 0,
      fontKerning: 'normal',
      textRendering: 'geometricPrecision',
      textShadow:
        '-1px -1px 2px rgba(0,0,0,0.95), 1px -1px 2px rgba(0,0,0,0.95), -1px 1px 2px rgba(0,0,0,0.95), 1px 1px 2px rgba(0,0,0,0.95), 0 0 8px rgba(0,0,0,0.5)',
      paintOrder: '',
      WebkitTextStroke: '',
      backgroundColor: 'transparent',
      backdropFilter: 'blur(6px)',
      fontWeight: '600',
      fontStyle: 'normal',
    },
  },
  subtitleSidebar: {
    enabled: true,
    autoOpen: false,
    layout: 'overlay',
    toggleKey: 'Backslash',
    pauseVideoOnHover: true,
    autoScroll: true,
    css: {},
    maxWidth: 420,
    opacity: 0.95,
    backgroundColor: 'rgba(73, 77, 100, 0.9)',
    textColor: '#cad3f5',
    fontFamily: 'Hiragino Sans, M PLUS 1, Source Han Sans JP, Noto Sans CJK JP',
    fontSize: 16,
    timestampColor: '#a5adcb',
    activeLineColor: '#f5bde6',
    activeLineBackgroundColor: 'rgba(138, 173, 244, 0.22)',
    hoverLineBackgroundColor: 'rgba(54, 58, 79, 0.84)',
  },
};
