import assert from 'node:assert/strict';
import test from 'node:test';
import { createMainBootRuntimes } from './runtimes';

test('createMainBootRuntimes returns grouped runtime bundles', () => {
  const runtimes = createMainBootRuntimes<any, any, any, any>({
    overlayVisibilityRuntimeDeps: {
      overlayVisibilityRuntime: {} as never,
      restorePreviousSecondarySubVisibilityMainDeps: {} as never,
      broadcastRuntimeOptionsChangedMainDeps: {} as never,
      sendToActiveOverlayWindowMainDeps: {} as never,
      setOverlayDebugVisualizationEnabledMainDeps: {} as never,
      openRuntimeOptionsPaletteMainDeps: {} as never,
    },
    jellyfinRuntimeHandlerDeps: {
      getResolvedJellyfinConfigMainDeps: {} as never,
      getJellyfinClientInfoMainDeps: {} as never,
      waitForMpvConnectedMainDeps: {} as never,
      launchMpvIdleForJellyfinPlaybackMainDeps: {} as never,
      ensureMpvConnectedForJellyfinPlaybackMainDeps: {} as never,
      preloadJellyfinExternalSubtitlesMainDeps: {} as never,
      playJellyfinItemInMpvMainDeps: {} as never,
      remoteComposerOptions: {} as never,
      handleJellyfinAuthCommandsMainDeps: {} as never,
      handleJellyfinListCommandsMainDeps: {} as never,
      handleJellyfinPlayCommandMainDeps: {} as never,
      handleJellyfinRemoteAnnounceCommandMainDeps: {} as never,
      startJellyfinRemoteSessionMainDeps: {} as never,
      stopJellyfinRemoteSessionMainDeps: {} as never,
      runJellyfinCommandMainDeps: {} as never,
      maybeFocusExistingJellyfinSetupWindowMainDeps: {} as never,
      openJellyfinSetupWindowMainDeps: {} as never,
    },
    anilistSetupDeps: {
      notifyDeps: {} as never,
      consumeTokenDeps: {} as never,
      handleProtocolDeps: {} as never,
      registerProtocolClientDeps: {} as never,
    },
    buildOpenAnilistSetupWindowMainDeps: {
      maybeFocusExistingSetupWindow: () => false,
      createSetupWindow: () => null as never,
      buildAuthorizeUrl: () => 'https://example.test',
      consumeCallbackUrl: () => false,
      openSetupInBrowser: () => {},
      loadManualTokenEntry: () => Promise.resolve(),
      redirectUri: 'https://example.test/callback',
      developerSettingsUrl: 'https://example.test/dev',
      isAllowedExternalUrl: () => true,
      isAllowedNavigationUrl: () => true,
      logWarn: () => {},
      logError: () => {},
      clearSetupWindow: () => {},
      setSetupPageOpened: () => {},
      setSetupWindow: () => {},
      openExternal: () => {},
    },
    anilistTrackingDeps: {
      refreshClientSecretMainDeps: {} as never,
      getCurrentMediaKeyMainDeps: {} as never,
      resetMediaTrackingMainDeps: {} as never,
      getMediaGuessRuntimeStateMainDeps: {} as never,
      setMediaGuessRuntimeStateMainDeps: {} as never,
      resetMediaGuessStateMainDeps: {} as never,
      maybeProbeDurationMainDeps: {} as never,
      ensureMediaGuessMainDeps: {} as never,
      processNextRetryUpdateMainDeps: {} as never,
      maybeRunPostWatchUpdateMainDeps: {} as never,
    },
    statsStartupRuntimeDeps: {
      ensureStatsServerStarted: () => '',
      ensureBackgroundStatsServerStarted: () => ({ url: '', runningInCurrentProcess: false }),
      stopBackgroundStatsServer: async () => ({ ok: true, stale: false }),
      ensureImmersionTrackerStarted: () => {},
    },
    runStatsCliCommandDeps: {
      getResolvedConfig: () => ({}) as never,
      ensureImmersionTrackerStarted: () => {},
      ensureVocabularyCleanupTokenizerReady: async () => {},
      getImmersionTracker: () => null,
      ensureStatsServerStarted: () => '',
      ensureBackgroundStatsServerStarted: () => ({ url: '', runningInCurrentProcess: false }),
      stopBackgroundStatsServer: async () => ({ ok: true, stale: false }),
      openExternal: () => Promise.resolve(),
      writeResponse: () => {},
      exitAppWithCode: () => {},
      logInfo: () => {},
      logWarn: () => {},
      logError: () => {},
    },
    appReadyRuntimeDeps: {
      reloadConfigMainDeps: {
        reloadConfigStrict: () => ({ ok: true, path: '/tmp/config.jsonc', warnings: [] }),
        logInfo: () => {},
        logWarning: () => {},
        showDesktopNotification: () => {},
        startConfigHotReload: () => {},
        refreshAnilistClientSecretState: async () => {},
        failHandlers: {
          logError: () => {},
          showErrorBox: () => {},
          quit: () => {},
        },
      },
      criticalConfigErrorMainDeps: {
        getConfigPath: () => '/tmp/config.jsonc',
        failHandlers: {
          logError: () => {},
          showErrorBox: () => {},
          quit: () => {},
        },
      },
      appReadyRuntimeMainDeps: {
        ensureDefaultConfigBootstrap: () => {},
        loadSubtitlePosition: () => {},
        resolveKeybindings: () => {},
        createMpvClient: () => {},
        getResolvedConfig: () => ({}) as never,
        getConfigWarnings: () => [],
        logConfigWarning: () => {},
        setLogLevel: () => {},
        initRuntimeOptionsManager: () => {},
        setSecondarySubMode: () => {},
        defaultSecondarySubMode: 'hover',
        defaultWebsocketPort: 5174,
        defaultAnnotationWebsocketPort: 6678,
        defaultTexthookerPort: 5174,
        hasMpvWebsocketPlugin: () => false,
        startSubtitleWebsocket: () => {},
        startAnnotationWebsocket: () => {},
        startTexthooker: () => {},
        log: () => {},
        createMecabTokenizerAndCheck: async () => {},
        createSubtitleTimingTracker: () => {},
        loadYomitanExtension: async () => {},
        handleFirstRunSetup: async () => {},
        startJellyfinRemoteSession: async () => {},
        prewarmSubtitleDictionaries: async () => {},
        startBackgroundWarmups: () => {},
        texthookerOnlyMode: false,
        shouldAutoInitializeOverlayRuntimeFromConfig: () => false,
        setVisibleOverlayVisible: () => {},
        initializeOverlayRuntime: () => {},
        handleInitialArgs: () => {},
        logDebug: () => {},
        now: () => Date.now(),
      },
      immersionTrackerStartupMainDeps: {
        getResolvedConfig: () => ({}) as never,
        getConfiguredDbPath: () => '/tmp/immersion.sqlite',
        createTrackerService: () =>
          ({
            startSession: () => {},
          }) as never,
        setTracker: () => {},
        getMpvClient: () => null,
        seedTrackerFromCurrentMedia: () => {},
        logInfo: () => {},
        logDebug: () => {},
        logWarn: () => {},
      },
    },
    mpvRuntimeDeps: {
      bindMpvMainEventHandlersMainDeps: {
        appState: {
          initialArgs: null,
          overlayRuntimeInitialized: true,
          mpvClient: null,
          immersionTracker: null,
          subtitleTimingTracker: null,
          currentSubText: '',
          currentSubAssText: '',
          playbackPaused: null,
          previousSecondarySubVisibility: null,
        },
        getQuitOnDisconnectArmed: () => false,
        scheduleQuitCheck: () => {},
        quitApp: () => {},
        reportJellyfinRemoteStopped: () => {},
        syncOverlayMpvSubtitleSuppression: () => {},
        maybeRunAnilistPostWatchUpdate: async () => {},
        logSubtitleTimingError: () => {},
        broadcastToOverlayWindows: () => {},
        onSubtitleChange: () => {},
        refreshDiscordPresence: () => {},
        ensureImmersionTrackerInitialized: () => {},
        updateCurrentMediaPath: () => {},
        restoreMpvSubVisibility: () => {},
        getCurrentAnilistMediaKey: () => null,
        resetAnilistMediaTracking: () => {},
        maybeProbeAnilistDuration: () => {},
        ensureAnilistMediaGuess: () => {},
        syncImmersionMediaState: () => {},
        updateCurrentMediaTitle: () => {},
        resetAnilistMediaGuessState: () => {},
        reportJellyfinRemoteProgress: () => {},
        updateSubtitleRenderMetrics: () => {},
      },
      mpvClientRuntimeServiceFactoryMainDeps: {
        createClient: class FakeMpvClient {
          connected = true;
          on(): void {}
          connect(): void {}
        } as never,
        getSocketPath: () => '/tmp/mpv.sock',
        getResolvedConfig: () => ({ auto_start_overlay: false }),
        isAutoStartOverlayEnabled: () => true,
        setOverlayVisible: () => {},
        isVisibleOverlayVisible: () => false,
        getReconnectTimer: () => null,
        setReconnectTimer: () => {},
      },
      updateMpvSubtitleRenderMetricsMainDeps: {
        getCurrentMetrics: () => ({
          subPos: 100,
          subFontSize: 36,
          subScale: 1,
          subMarginY: 0,
          subMarginX: 0,
          subFont: '',
          subSpacing: 0,
          subBold: false,
          subItalic: false,
          subBorderSize: 0,
          subShadowOffset: 0,
          subAssOverride: 'yes',
          subScaleByWindow: true,
          subUseMargins: true,
          osdHeight: 0,
          osdDimensions: null,
        }),
        setCurrentMetrics: () => {},
        applyPatch: (current: any) => ({ next: current, changed: false }),
        broadcastMetrics: () => {},
      },
      tokenizer: {
        buildTokenizerDepsMainDeps: {
          getYomitanExt: () => null,
          getYomitanParserWindow: () => null,
          setYomitanParserWindow: () => {},
          getYomitanParserReadyPromise: () => null,
          setYomitanParserReadyPromise: () => {},
          getYomitanParserInitPromise: () => null,
          setYomitanParserInitPromise: () => {},
          isKnownWord: () => false,
          recordLookup: () => {},
          getKnownWordMatchMode: () => 'headword',
          getMinSentenceWordsForNPlusOne: () => 3,
          getJlptLevel: () => null,
          getJlptEnabled: () => false,
          getFrequencyDictionaryEnabled: () => false,
          getFrequencyDictionaryMatchMode: () => 'headword',
          getFrequencyRank: () => null,
          getYomitanGroupDebugEnabled: () => false,
          getMecabTokenizer: () => null,
        },
        createTokenizerRuntimeDeps: () => ({}),
        tokenizeSubtitle: async () => ({ text: '' }),
        createMecabTokenizerAndCheckMainDeps: {
          getMecabTokenizer: () => null,
          setMecabTokenizer: () => {},
          createMecabTokenizer: () => ({}) as never,
          checkAvailability: async () => {},
        },
        prewarmSubtitleDictionariesMainDeps: {
          ensureJlptDictionaryLookup: async () => {},
          ensureFrequencyDictionaryLookup: async () => {},
        },
      },
      warmups: {
        launchBackgroundWarmupTaskMainDeps: {
          now: () => 0,
          logDebug: () => {},
          logWarn: () => {},
        },
        startBackgroundWarmupsMainDeps: {
          getStarted: () => false,
          setStarted: () => {},
          isTexthookerOnlyMode: () => false,
          ensureYomitanExtensionLoaded: async () => {},
          shouldWarmupMecab: () => false,
          shouldWarmupYomitanExtension: () => false,
          shouldWarmupSubtitleDictionaries: () => false,
          shouldWarmupJellyfinRemoteSession: () => false,
          shouldAutoConnectJellyfinRemote: () => false,
          startJellyfinRemoteSession: async () => {},
        },
      },
    },
    trayRuntimeDeps: {
      resolveTrayIconPathDeps: {} as never,
      buildTrayMenuTemplateDeps: {} as never,
      ensureTrayDeps: {} as never,
      destroyTrayDeps: {} as never,
      buildMenuFromTemplate: () => ({}) as never,
    },
    yomitanProfilePolicyDeps: {
      externalProfilePath: '',
      logInfo: () => {},
    },
    yomitanExtensionRuntimeDeps: {
      loadYomitanExtensionCore: async () => null,
      userDataPath: '/tmp',
      externalProfilePath: '',
      getYomitanParserWindow: () => null,
      setYomitanParserWindow: () => {},
      setYomitanParserReadyPromise: () => {},
      setYomitanParserInitPromise: () => {},
      setYomitanExtension: () => {},
      setYomitanSession: () => {},
      getYomitanExtension: () => null,
      getLoadInFlight: () => null,
      setLoadInFlight: () => {},
    },
    yomitanSettingsRuntimeDeps: {
      ensureYomitanExtensionLoaded: async () => {},
      getYomitanSession: () => null,
      openYomitanSettingsWindow: () => {},
      getExistingWindow: () => null,
      setWindow: () => {},
      logWarn: () => {},
      logError: () => {},
    },
    createOverlayRuntimeBootstrapHandlers: () => ({
      initializeOverlayRuntime: () => {},
    }),
    initializeOverlayRuntimeMainDeps: {},
    initializeOverlayRuntimeBootstrapDeps: {},
  });

  assert.equal(typeof runtimes.overlayVisibilityComposer.sendToActiveOverlayWindow, 'function');
  assert.equal(typeof runtimes.jellyfinRuntimeHandlers.runJellyfinCommand, 'function');
  assert.equal(typeof runtimes.anilistSetupHandlers.notifyAnilistSetup, 'function');
  assert.equal(typeof runtimes.openAnilistSetupWindow, 'function');
  assert.equal(typeof runtimes.anilistTrackingHandlers.maybeRunAnilistPostWatchUpdate, 'function');
  assert.equal(typeof runtimes.runStatsCliCommand, 'function');
  assert.equal(typeof runtimes.appReadyRuntime.appReadyRuntimeRunner, 'function');
  assert.equal(typeof runtimes.initializeOverlayRuntime, 'function');
});
